### ISSUE TITLE
Discrepancies between ToulligQC and PycoQC

### ISSUE THREAD

**Issue by sklages** [GenomiqueENS/toulligQC#29]
There are quite significant discrepancies between [pycoQC](https://github.com/a-slide/pycoQC) and ToulligQC numbers and plots (based on passed data) when run on the same dataset.

That is probably due to the _definition_ of "**passed**" for a read, that will most likely influence (all) subsequent calculations based on "**passed**" reads.

Can you provide a definition of what it needs for a read to be considered "passed" by ToulligQC?

**Comment by alihamraoui** [comment]
Hi @sklages,

A read is considered "passed" if its mean quality score is above a Phred score threshold. By default, this value is set to a Phred score of 9 in ToulligQC 2.7.

I believe the threshold in pycoQC is set to 7, which is why there are discrepancies between the ToulligQC and pycoQC numbers. You can adjust this value in ToulligQC using the `--qscore-threshold` flag. 

We set it to 9 due to the significant improvements in the latest Nanopore chemistry.

Ali

**Comment by sklages** [comment]
@alihamraoui - thank you for clarification! That makes perfectly sense :-)
